name: Extract

on:
  schedule:
    - cron: '1 0 * * 1'

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fail-fast:
          - false
        source:
          - nobelgo
          - cigarworld
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Build binary
        run: make build
      - name: Extract data
        run: make extract SOURCE=${{ matrix.source }} DIR_OUT=${PWD}/tmp/${{ matrix.source }}
      - name: Checkout data branch
        run: git checkout data
      - name: Move to persistence dir
        run: mv ${PWD}/tmp/${{ matrix.source }}/*.json ${PWD}/data/${{ matrix.source}}/
      - name: Commit and push
        run: |
          git config --global user.name "Dmitry Kisler"
          git config --global user.email "admin@dkisler.com"
          git add ${PWD}/tmp/${{ matrix.source }}/*.json
          git commit -S -m 'add extract from ${{ matrix.source }} as of $(date -u "+ %Y-%m-%d"). Signed-off by: Dmitry Kisler <admin@dkisler.com>'
          git fetch origin
          git rebase --strategy-option=theirs origin/data
          git push
