name: Tests

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '*.go'
      - '**/*.go'
      - '**/testdata'
  push:
    branches:
      - master
    paths:
      - 'go.mod'
      - 'go.sum'
      - '*.go'
      - '**/*.go'
      - '**/testdata'

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@051d91933864810ecd5e2ea2cfd98f6a5bca5347 # v6.3.2
        with:
          version: latest
      - name: Run tests
        run: make test
